### ISSUE TITLE
correlation of 0.99?

### ISSUE THREAD

**Issue by jovo** [Upward-Spiral-Science/the-fat-boys#6]
i thought i saw a figure one day from you guys showing a correlation of nearly 0.99 between 2 VGlut1 channels after log transforming the data? can you send me a link to that figure again, assuming i recall correctly?

@ikuznet1 @khuang28jhu @mrae

**Comment by fatboy1** [comment]
Hi Jovo I think our team and Jesse have done much work checking the correlation of the 2 Vglut1 channels, i.e. looking at correlation matrices, clustering etc to look at how close they are, but I don't recall having a precise figure of 0.99. I have attached some figures here from my report, Jesse's code on neurodata and also Ivan's report. I think you might be referring to Jesse's figure since his correlation matrix seem to very nicely show that there is high correlation between the two vglut1 channels. Thanks a lot!

![screen shot 2016-05-04 at 11 10 57 pm](https://cloud.githubusercontent.com/assets/5505492/15035230/c2be01d6-124d-11e6-8c59-6c0d7133e3ca.png)
![screen shot 2016-05-04 at 11 14 40 pm](https://cloud.githubusercontent.com/assets/5505492/15035260/082524f2-124e-11e6-8d22-ce119428bc7b.png)
![screen shot 2016-05-04 at 11 18 18 pm](https://cloud.githubusercontent.com/assets/5505492/15035305/8778fa80-124e-11e6-8796-7703ceeecb99.png)

**Comment by fatboy1** [comment]
PS. We will make our figures look much nicer in the final report

**Comment by fatboy1** [comment]
Jesse's figure above is taken from figure 17 of http://docs.neurodata.io/synaptome-stats/Code/hkmeans.html

**Comment by ikuznet1** [comment]
I computed the correlation and get a value of 0.8558544 (in the int brightness channel).

Here is a heatmap:
![correlation](https://cloud.githubusercontent.com/assets/11143517/15035492/6e2577aa-1250-11e6-9b4a-fb7cf9891833.png)

**Comment by jovo** [comment]
@ikuznet1 can you clarify/provide details?

On Wed, May 4, 2016 at 11:27 PM, ikuznet1 notifications@github.com wrote:

> I computed the correlation and get a value of 0.8558544 (in the int
> brightness channel).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/the-fat-boys/issues/6#issuecomment-217069840

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
